# Generated by Django 3.2.8 on 2021-10-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211019_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creadit_card',
            new_name='credit_card',
        ),
    ]
