# Generated by Django 3.2.8 on 2021-10-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211020_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencies',
            options={'verbose_name': 'Currencie'},
        ),
        migrations.AlterModelOptions(
            name='proposals',
            options={'verbose_name': 'Proposal'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'verbose_name': 'Transaction'},
        ),
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name': 'Tutorial'},
        ),
        migrations.AlterModelOptions(
            name='userkyc',
            options={'verbose_name': 'KYC Document'},
        ),
    ]
