# Generated by Django 3.2.8 on 2021-10-26 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?46?\\d{8,15}$')]),
        ),
    ]
