# Generated by Django 3.2.8 on 2021-10-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211026_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
