# Generated by Django 3.2.8 on 2021-10-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkyc',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
