# Generated by Django 3.2.8 on 2021-10-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userkyc_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkyc',
            name='comments',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
