# Generated by Django 3.2.8 on 2021-10-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211027_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkyc',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
