# Generated by Django 3.2.8 on 2021-10-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211027_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkyc',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
