# Generated by Django 3.2.8 on 2021-10-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_userkyc_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposals',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, help_text='max amount 100 000 000', verbose_name='Total Balance'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='currency',
            field=models.CharField(help_text='Max limit is 4 (Alphabets, Digits)', max_length=4, verbose_name='Currency Name'),
        ),
        migrations.AlterField(
            model_name='proposals',
            name='details',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
