# Generated by Django 3.2.8 on 2021-10-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211027_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposals',
            name='files',
        ),
    ]
