# Generated by Django 3.2.8 on 2021-10-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211027_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorials',
            name='cover',
            field=models.ImageField(blank=True, default='Profiles/user/user.png', null=True, upload_to='covers/%Y/%m/%d/'),
        ),
    ]
