# Generated by Django 3.2.8 on 2021-10-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_tutorials_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='name',
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='cover',
            field=models.ImageField(blank=True, default='covers/cover.jpg', null=True, upload_to='covers/%Y/%m/%d/'),
        ),
    ]
